AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ToDoUser:
    Description: Name of User Table
    Type: String
    Default: ToDoUser
  ToDoTask:
    Description: Name of To Do Task Table
    Type: String
    Default: ToDoTask
Resources:

# ===================== Dynamo DB Resource =========================
  ToDoUserTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName:
        Ref: ToDoUser
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
    DependsOn:
      - APIGatewayPermission

  ToDoTaskTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName:
        Ref: ToDoTask
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
    DependsOn:
      - APIGatewayPermission